import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Great_Vibes } from "next/font/google";
import { Bitcount_Prop_Single } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tap Tap Trivia", 
  description: "Generated by create next app",
};

const greatVibes = Great_Vibes({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-great-vibes",
});

const bitcount = Bitcount_Prop_Single({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-bitcount",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
    ${geistSans.variable} 
    ${geistMono.variable} 
    ${greatVibes.variable}
    ${bitcount.variable}
    antialiased
  `}
      >
        {children}
      </body>
    </html>
  );
}